-- Phase 4 Migration: Advanced Refinements

-- 1. Enhance Products Table
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'General';
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS gallery TEXT[] DEFAULT '{}';
ALTER TABLE products ADD COLUMN IF NOT EXISTS cogs NUMERIC DEFAULT 0;

-- 2. Create Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    admin_id TEXT, -- Can be 'system' or an admin identifier
    action TEXT NOT NULL, -- e.g., 'UPDATE_STOCK', 'CHANGE_PRICE'
    entity_type TEXT NOT NULL, -- e.g., 'product', 'order'
    entity_id TEXT NOT NULL,
    old_value JSONB,
    new_value JSONB,
    metadata JSONB
);

-- 3. Create Admin Users table (for Role-based Access)
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL, -- In a real app, use auth.users, but here we follow the custom auth pattern
    role TEXT DEFAULT 'staff', -- 'admin' or 'staff'
    last_login TIMESTAMP WITH TIME ZONE
);

-- 4. Enable RLS and setup public access
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Audit Logs' AND tablename = 'audit_logs') THEN
        CREATE POLICY "Public Access Audit Logs" ON audit_logs FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Admin Users' AND tablename = 'admin_users') THEN
        CREATE POLICY "Public Access Admin Users" ON admin_users FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
