-- Migration for New Features Added to the Store

-- 1. store_config additions
ALTER TABLE store_config ADD COLUMN IF NOT EXISTS city_delivery_days JSONB DEFAULT '{}'::jsonb;

-- 2. orders additions
ALTER TABLE orders ADD COLUMN IF NOT EXISTS whatsapp_optin BOOLEAN DEFAULT false;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS admin_notes TEXT;

-- 3. Products table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    sale_price TEXT,
    stock INT DEFAULT 99,
    image_url TEXT,
    active BOOLEAN DEFAULT true
);

-- 4. Return Requests table
CREATE TABLE IF NOT EXISTS return_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
    customer_name TEXT,
    customer_phone TEXT,
    reason TEXT,
    details TEXT,
    status TEXT DEFAULT 'Pending'
);

-- 5. Abandoned Carts table
CREATE TABLE IF NOT EXISTS abandoned_carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    phone TEXT UNIQUE NOT NULL,
    name TEXT,
    city TEXT,
    last_seen TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    recovered BOOLEAN DEFAULT false
);

-- 6. Message Templates table
CREATE TABLE IF NOT EXISTS message_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    category TEXT DEFAULT 'Order',
    template_text TEXT NOT NULL
);

-- 7. Coupons table
CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    code TEXT UNIQUE NOT NULL,
    type TEXT DEFAULT 'percent',
    value NUMERIC NOT NULL,
    min_order NUMERIC DEFAULT 0,
    active BOOLEAN DEFAULT true
);

-- 8. Customer Reviews table
CREATE TABLE IF NOT EXISTS customer_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    location TEXT,
    review TEXT NOT NULL,
    rating INT DEFAULT 5,
    tag TEXT,
    verified BOOLEAN DEFAULT true,
    active BOOLEAN DEFAULT true
);

-- Enable RLS and setup public access
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE return_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE abandoned_carts ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_reviews ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Products' AND tablename = 'products') THEN
        CREATE POLICY "Public Access Products" ON products FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Returns' AND tablename = 'return_requests') THEN
        CREATE POLICY "Public Access Returns" ON return_requests FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Carts' AND tablename = 'abandoned_carts') THEN
        CREATE POLICY "Public Access Carts" ON abandoned_carts FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Templates' AND tablename = 'message_templates') THEN
        CREATE POLICY "Public Access Templates" ON message_templates FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Coupons' AND tablename = 'coupons') THEN
        CREATE POLICY "Public Access Coupons" ON coupons FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Reviews' AND tablename = 'customer_reviews') THEN
        CREATE POLICY "Public Access Reviews" ON customer_reviews FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
