-- Quiz Leads Table for Marketing
CREATE TABLE IF NOT EXISTS quiz_leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT,
    email TEXT,
    phone TEXT,
    responses JSONB, -- Store quiz answers
    recommended_product TEXT,
    converted BOOLEAN DEFAULT false
);

-- Enable RLS
ALTER TABLE quiz_leads ENABLE ROW LEVEL SECURITY;

-- Setup Policies
DO $$ 
BEGIN
    -- Public Insert Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Quiz Lead Submission' AND tablename = 'quiz_leads') THEN
        CREATE POLICY "Public Quiz Lead Submission" ON quiz_leads 
            FOR INSERT 
            WITH CHECK (true);
    END IF;

    -- Admin Select Policy
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Admin View Leads' AND tablename = 'quiz_leads') THEN
        CREATE POLICY "Admin View Leads" ON quiz_leads 
            FOR SELECT 
            USING (auth.role() = 'authenticated');
    END IF;
END $$;
