-- 1. Create store_config table if it doesn't exist
CREATE TABLE IF NOT EXISTS store_config (
    id INT PRIMARY KEY DEFAULT 1,
    admin_password TEXT DEFAULT '0000',
    product_price NUMERIC DEFAULT 1700,
    cod_shipping_fee NUMERIC DEFAULT 100,
    jazzcash_discount NUMERIC DEFAULT 10,
    accepting_orders BOOLEAN DEFAULT true,
    is_sale_active BOOLEAN DEFAULT false,
    sale_multiplier NUMERIC DEFAULT 0.8,
    announcement_text TEXT DEFAULT '✨ Welcome to The Essential Cure ✨',
    jazzcash_name TEXT DEFAULT 'Admin Account',
    jazzcash_number TEXT DEFAULT '03000000000',
    whatsapp_number TEXT DEFAULT '923000000000',
    current_stock INT DEFAULT 100,
    low_stock_threshold INT DEFAULT 5,
    cancellation_window_mins INT DEFAULT 15,
    store_closed_message TEXT DEFAULT 'We are currently restockng. Check back soon!'
);

-- Ensure a single config row exists
INSERT INTO store_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- 2. Add Phase 5 columns if they don't exist (safety check)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='store_config' AND column_name='low_stock_threshold') THEN
        ALTER TABLE store_config ADD COLUMN low_stock_threshold INT DEFAULT 5;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='store_config' AND column_name='cancellation_window_mins') THEN
        ALTER TABLE store_config ADD COLUMN cancellation_window_mins INT DEFAULT 15;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='store_config' AND column_name='store_closed_message') THEN
        ALTER TABLE store_config ADD COLUMN store_closed_message TEXT DEFAULT 'We are currently restockng. Check back soon!';
    END IF;
END $$;

-- 3. Create Orders table
CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_city TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    customer_notes TEXT,
    quantity INT DEFAULT 1,
    payment_method TEXT DEFAULT 'COD',
    shipping_fee NUMERIC DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Processing',
    cancel_reason TEXT
);

-- 4. Create JazzCash Payments table
CREATE TABLE IF NOT EXISTS jazzcash_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
    receipt_url TEXT NOT NULL
);

-- 5. Enable RLS
ALTER TABLE store_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE jazzcash_payments ENABLE ROW LEVEL SECURITY;

-- 6. Grant Public Access (Update for your security needs)
-- Drop existing the first time if needed, but for setup we'll use CREATE if not exists
DO $$ 
BEGIN
    -- Config: Public Select/Update
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Config' AND tablename = 'store_config') THEN
        CREATE POLICY "Public Access Config" ON store_config FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Orders: Public Select/Insert/Update (Update for cancellation/status)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Orders' AND tablename = 'orders') THEN
        CREATE POLICY "Public Access Orders" ON orders FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Payments: Public Select/Insert
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Payments' AND tablename = 'jazzcash_payments') THEN
        CREATE POLICY "Public Access Payments" ON jazzcash_payments FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
